### ISSUE TITLE
Top Page Image［Mobile］

### ISSUE THREAD

**Issue by naztshinozaki** [bidish-acharya/Yakatabune-Project#11]
The Tokyo舟遊び。words on the top page image are not made responsive in Mobile. 
![36052216_10216193012363872_2034448788898185216_n](https://user-images.githubusercontent.com/19689481/41897684-f48f7626-7962-11e8-800d-36d10eae21c4.jpg)

**Comment by bidish-acharya** [comment]
Issue is solved.
