### ISSUE TITLE
Plus sign［Mobile］

### ISSUE THREAD

**Issue by naztshinozaki** [bidish-acharya/Yakatabune-Project#12]
The plus sign for the drop down menu bar is not aligned with the words. Please do check for all the plus signs and make sure that they are aligned.
![36223205_10216193012483875_1319954569454682112_n](https://user-images.githubusercontent.com/19689481/41898327-b2f23d0a-7964-11e8-85e4-212725dd48da.jpg)

**Comment by mayaogasawara** [comment]
@bidish-acharya 

Issue closed. Ignore this issue.
