### ISSUE TITLE
Bottom Nav Menu［Mobile］

### ISSUE THREAD

**Issue by naztshinozaki** [bidish-acharya/Yakatabune-Project#14]
The word on the bottom nav currently is "Food"（お料理）when it should be "Sitemap"（サイトマップ）。
Please replace the work with サイトマップ
![36064496_10216193012563877_5774781007773302784_n](https://user-images.githubusercontent.com/19689481/41898536-3f16bfd6-7965-11e8-8223-0f097d47352c.jpg)

**Comment by naztshinozaki** [comment]
When the plus sign is clicked and the dropdown menu appears, there is no minus sign to close the menu. Please add in the minus sign. 
![36188390_10216193012203868_7812469950064361472_n](https://user-images.githubusercontent.com/19689481/41899031-60082134-7966-11e8-93d3-547fbe445ce7.jpg)

**Comment by bidish-acharya** [comment]
I have solved the issue.
