### ISSUE TITLE
Menu-Bar

### ISSUE THREAD

**Issue by mayaogasawara** [bidish-acharya/Yakatabune-Project#17]
@bidish-acharya 

Here, I changed the menu contents based on Kimura san's layout. Please see below.
https://docs.google.com/document/d/1K6J9_WbUF2-6QkZ2OISwLf1r2XtyatjM-rszdZOGAxQ/edit?usp=sharing

Thanks,
Maya

**Comment by bidish-acharya** [comment]
@mayaogasawara 

I have solved this issue.
