### ISSUE TITLE
Google Analytics Code

### ISSUE THREAD

**Issue by mayaogasawara** [bidish-acharya/Yakatabune-Project#22]
Please include the following google analytics code.
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-105356754-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-105356754-1');
</script>
`

**Comment by mayaogasawara** [comment]
@bidish-acharya 

Seems the code is not showing up on issues correctly, I will send an email with the code.

**Comment by bidish-acharya** [comment]
Solved.
