### ISSUE TITLE
CONTACT: Graphic Change 

### ISSUE THREAD

**Issue by mayaogasawara** [bidish-acharya/Yakatabune-Project#3]
![dash_ _margin](https://user-images.githubusercontent.com/40377660/41705276-7e995cd6-7573-11e8-8e6c-1fddd4644bdd.png)

1. Delete dash lines (-----------)around the section. 
2. Compare the top and bottom margin. Right now, the top margin looks narrower than the bottom. Try to adjust the space so that the margins are visually even out in relation to the texts, and are aesthetically pleasing. It would be better if you study how it looks like in the original design, and try to imitate that proportion.

**Comment by bidish-acharya** [comment]
The dashed lines have been deleted and the margins are made even.
