### ISSUE TITLE
MOBILE ONLY: Remove Effect

### ISSUE THREAD

**Issue by mayaogasawara** [bidish-acharya/Yakatabune-Project#5]
Is there zoom in/out effect like it shows on Mobile ver(we could not check on the mobile screen)? If so, you can remove the zoom in/out effect from the Mobile version. ( We like the effect ONLY on pc version)
![mobile_effect](https://user-images.githubusercontent.com/40377660/41706790-a1ea515a-7577-11e8-8a87-bf963f9b375c.png)

**Comment by bidish-acharya** [comment]
The effects have been removed.
