### ISSUE TITLE
MOBILE: Using Image 

### ISSUE THREAD

**Issue by mayaogasawara** [bidish-acharya/Yakatabune-Project#6]
Right now this logo(circled) below is a combination of the logo image and the text. 
It should be a single image embedded there (the image includes both the logo and the text)

Kimura-san thinks she outlined a logo including text (the part I indicated below should be a single image)in the original file. 

![logo_image](https://user-images.githubusercontent.com/40377660/41707102-547b522e-7578-11e8-8a88-373b9e38ab17.png)

Is it possible for you to check the original ai file to find the outlined logo and replace it? If you cannot find the image, please let me and kimura san know. She will send it again.

**Comment by bidish-acharya** [comment]
Hi Maya Ma'am,,

I think that is a single image. I have attached a single image. I have used two different logo images for PC and Smartphone version. Please verify and let me know.

![logo-sm](https://user-images.githubusercontent.com/40300806/41721255-23936928-7585-11e8-9920-76bc5eca7141.png)

**Comment by mayaogasawara** [comment]
@Hiroko-Kimura 

ひろこさん、

上のロゴであってますか？もし違っていたらアウトライン化したものをもう一度送ってください。
お手数おかけして申し訳ありません。

摩耶

**Comment by mayaogasawara** [comment]
@bidish-acharya 
Kimura san will send new logo. She will need some time:) She will let you know when it is ready.

**Comment by bidish-acharya** [comment]
@mayaogasawara 

Done. Please verify!
