### ISSUE TITLE
to MAYA san  /0625 change 

### ISSUE THREAD

**Issue by Hiroko-Kimura** [bidish-acharya/Yakatabune-Project#8]
摩耶さん

お世話になります。
修正取りまとめて見ました。
確認お願いします。
トップページは
もう少し詰めたい箇所がありますがとりあえず一旦こちらの修正を
完了していただきたいです。

https://goo.gl/HWWDxd

これ以外にお願いしたいことは
アレックスと今週予定が合わなくて会えないので
フォントのことをbidishさんの方でトライしていただきたいです。

１スマフォで見るとゴシックになってしまうこと
２windosでゴシックに見えてしまうことがあること

以上よろしくおねがします。

**Comment by mayaogasawara** [comment]
すごくわかりやすいです！
ありがとうございます。フォントも了解致しました。

小笠原

**Comment by Hiroko-Kimura** [comment]
摩耶さん

ありがとうございます。
ネパールでも見られるといいのですが。よろしくお願いします！

ひろこ

**Comment by mayaogasawara** [comment]
@bidish-acharya 

This issue is already closed. No need to do it.
